"""Schema layer for consent/disclosure generation contracts."""

from engine.schemas.case_facts_schema import CaseFacts, CaseFactsSchema
from engine.schemas.common import (
    AIRoleEnum,
    ClinicalDomainEnum,
    CommunicationChannelEnum,
    ConsentDocumentAudienceEnum,
    ConsentDocumentTypeEnum,
    ContentTypeEnum,
    DecisionTypeEnum,
    DocumentSectionIdEnum,
    EntityEnum,
    EvaluationItemKindEnum,
    FormatConstraintEnum,
    FunctionCategoryEnum,
    HumanLicensedReviewEnum,
    IndependentEvaluationEnum,
    JurisdictionEnum,
    ModelChangesEnum,
    PrimaryUserEnum,
    RequirementTypeEnum,
    SchemaValidationError,
    SensitiveInformationEnum,
    TimingRuleEnum,
)
from engine.schemas.consent_brief_schema import (
    BriefSectionRequirementSchema,
    ConsentDocumentAudience,
    ConsentDocumentBrief,
    ConsentDocumentBriefSchema,
    ConsentDocumentType,
)
from engine.schemas.evaluation_result_schema import (
    DerivedFactsSchema,
    EvaluationItem,
    EvaluationItemSchema,
    EvaluationResult,
    EvaluationResultSchema,
)
from engine.schemas.document_validation_schema import (
    DocumentValidationResult,
    DocumentValidationResultSchema,
)
from engine.schemas.generated_document_schema import (
    DocumentSection,
    DocumentSectionSchema,
    GeneratedDocument,
    GeneratedDocumentSchema,
    SignatureBlockSchema,
)

__all__ = [
    "AIRoleEnum",
    "BriefSectionRequirementSchema",
    "CaseFacts",
    "CaseFactsSchema",
    "ClinicalDomainEnum",
    "CommunicationChannelEnum",
    "ConsentDocumentAudience",
    "ConsentDocumentAudienceEnum",
    "ConsentDocumentBrief",
    "ConsentDocumentBriefSchema",
    "ConsentDocumentType",
    "ConsentDocumentTypeEnum",
    "ContentTypeEnum",
    "DecisionTypeEnum",
    "DerivedFactsSchema",
    "DocumentSection",
    "DocumentSectionIdEnum",
    "DocumentSectionSchema",
    "DocumentValidationResult",
    "DocumentValidationResultSchema",
    "EntityEnum",
    "EvaluationItem",
    "EvaluationItemKindEnum",
    "EvaluationItemSchema",
    "EvaluationResult",
    "EvaluationResultSchema",
    "FormatConstraintEnum",
    "FunctionCategoryEnum",
    "GeneratedDocument",
    "GeneratedDocumentSchema",
    "HumanLicensedReviewEnum",
    "IndependentEvaluationEnum",
    "JurisdictionEnum",
    "ModelChangesEnum",
    "PrimaryUserEnum",
    "RequirementTypeEnum",
    "SchemaValidationError",
    "SensitiveInformationEnum",
    "SignatureBlockSchema",
    "TimingRuleEnum",
]
